<a href="https://colab.research.google.com/github/databyhuseyn/DeepLearning/blob/main/Deep_Learning_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
print(tf.__version__)

2.18.0


In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[5., 5.],
                              [5., 5.],
                              [5., 5.]], dtype = tf.float32)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[5., 5.],
       [5., 5.],
       [5., 5.]], dtype=float32)>

In [10]:
another_matrix.ndim

2

In [11]:
changeable_tensor = tf.Variable([5, 7])
unchangeable_tensor = tf.constant([5, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 7], dtype=int32)>)

In [12]:
changeable_tensor[0].assign(2)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

In [65]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3, 3))
random_1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535806 ]], dtype=float32)>

In [14]:
not_shuffled = tf.constant([[1, 5],
                            [7, 9],
                            [3, 8]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [7, 9],
       [3, 8]], dtype=int32)>

In [15]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [3, 8],
       [7, 9]], dtype=int32)>

In [74]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [7, 9],
       [3, 8]], dtype=int32)>

In [17]:
tf.ones([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [18]:
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [19]:
import numpy as np

numpy_A = np.arange(1, 25, dtype = np.int32)

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
A = tf.constant(numpy_A, shape = (2, 2, 2, 3))
A

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]], dtype=int32)>

In [21]:
zeros = tf.zeros([1, 2, 3, 4, 5, 4])
zeros

<tf.Tensor: shape=(1, 2, 3, 4, 5, 4), dtype=float32, numpy=
array([[[[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]],


         [[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]

In [22]:
tf.rank(zeros)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [23]:
A.shape, A.ndim, tf.size(A), tf.rank(A)

(TensorShape([2, 2, 2, 3]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [24]:
def info_about_tensor(tensor):
  print("Data type of every element: ", tensor.dtype)
  print("Number of dimensions (Rank): ", tf.rank(tensor))
  print("Shape of tensor: ", tensor.shape)
  print("Elements along the 0 axis: ", tensor.shape[0])
  print("Elements along the last axis: ", tensor.shape[-1])
  print("Total number of elements in our tensor: ", tf.size(tensor).numpy())


In [25]:
info_about_tensor(A)

Data type of every element:  <dtype: 'int32'>
Number of dimensions (Rank):  tf.Tensor(4, shape=(), dtype=int32)
Shape of tensor:  (2, 2, 2, 3)
Elements along the 0 axis:  2
Elements along the last axis:  3
Total number of elements in our tensor:  24


In [26]:
rank_2_tensor = tf.ones(shape = (2, 3))
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [27]:
tf.rank(rank_2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [28]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [29]:
tf.expand_dims(rank_2_tensor, axis=2)       # axis hara elave etdiyini gosterir

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [30]:
tensor = tf.constant([[10, 6],
                      [6, 9]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 16],
       [16, 19]], dtype=int32)>

In [31]:
tensor * 10

# or

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  60],
       [ 60,  90]], dtype=int32)>

In [32]:
tf.matmul(tensor, tensor)   # matrix multipication --> dot product

# OR

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[136, 114],
       [114, 117]], dtype=int32)>

In [33]:
X = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
Y = tf.constant([[7, 8, 9],
                 [10, 11, 12]])

X, Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [34]:
Y = tf.transpose(Y)
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]], dtype=int32)>

In [35]:
X @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [36]:
tf.matmul(X, Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [37]:
tf.reshape(Y, shape= (2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 10,  8],
       [11,  9, 12]], dtype=int32)>

In [38]:
X, Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7, 10],
        [ 8, 11],
        [ 9, 12]], dtype=int32)>)

In [39]:
tf.tensordot(X, Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [40]:
A = tf.constant([4, 5])
A.dtype

tf.int32

In [41]:
A = tf.cast(A, dtype = tf.int16)

In [42]:
A.dtype

tf.int16

In [43]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([46, 53, 76, 50, 44, 87, 88, 99, 94, 76, 47,  8, 16, 15, 78,  8, 81,
       32, 49, 23, 65, 34, 80, 69, 24, 36, 46, 90, 11, 59, 66, 49,  3, 42,
       94, 55, 43,  5, 96, 71, 19, 21, 70, 89, 17, 49, 96, 99, 21, 93])>

In [44]:
E.dtype

tf.int64

In [79]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = [1, 1, 1, 1, 50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [46]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [47]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [48]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [49]:
!nvidia-smi

Thu Mar  6 15:19:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P0             29W /   70W |     106MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# Hands-On Q/A

In [50]:
scalar = tf.constant(7)

In [51]:
vector = tf.constant([5, 6])

In [52]:
matrix = tf.constant([[5, 6],
                      [7, 8]])

In [53]:
scalar, vector, matrix

(<tf.Tensor: shape=(), dtype=int32, numpy=7>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 6],
        [7, 8]], dtype=int32)>)

In [54]:
matrix.shape, tf.rank(matrix), tf.size(matrix)

(TensorShape([2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [55]:
A = tf.random.normal(shape=[5, 300])
B = tf.random.normal(shape=[5, 300])

In [56]:
A @ tf.transpose(B)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-19.700886 ,   1.9933586,  -7.9026885,  19.950588 , -19.122309 ],
       [ -6.0533395,  12.41919  ,  22.246258 ,  20.91207  ,   6.415559 ],
       [  9.499851 ,  -2.309708 ,   7.6603174, -12.769201 ,   2.474299 ],
       [ 17.098804 ,  11.836249 , -15.267179 ,   0.7997595, -10.531876 ],
       [  9.99485  ,  45.66733  ,  13.350242 , -28.353817 ,   8.682101 ]],
      dtype=float32)>

In [57]:
tf.matmul(A, tf.transpose(B))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-19.700886 ,   1.9933586,  -7.9026885,  19.950588 , -19.122309 ],
       [ -6.0533395,  12.41919  ,  22.246258 ,  20.91207  ,   6.415559 ],
       [  9.499851 ,  -2.309708 ,   7.6603174, -12.769201 ,   2.474299 ],
       [ 17.098804 ,  11.836249 , -15.267179 ,   0.7997595, -10.531876 ],
       [  9.99485  ,  45.66733  ,  13.350242 , -28.353817 ,   8.682101 ]],
      dtype=float32)>

In [58]:
tf.tensordot(A, tf.transpose(B), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-19.700886 ,   1.9933586,  -7.9026885,  19.950588 , -19.122309 ],
       [ -6.0533395,  12.41919  ,  22.246258 ,  20.91207  ,   6.415559 ],
       [  9.499851 ,  -2.309708 ,   7.6603174, -12.769201 ,   2.474299 ],
       [ 17.098804 ,  11.836249 , -15.267179 ,   0.7997595, -10.531876 ],
       [  9.99485  ,  45.66733  ,  13.350242 , -28.353817 ,   8.682101 ]],
      dtype=float32)>

In [59]:
C = tf.random.normal(shape=[224, 224, 3])

In [60]:
tf.reduce_min(C[0]), tf.reduce_max(C[0])

(<tf.Tensor: shape=(), dtype=float32, numpy=-3.101553440093994>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.19816517829895>)

In [61]:
D = tf.random.normal(shape=[1, 224, 224, 3])

In [62]:
D_squeezed = tf.squeeze(D)
D_squeezed

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 0.00924649, -0.66206276, -0.7410269 ],
        [ 1.1985261 ,  0.86362076,  0.39257562],
        [ 0.93457496, -0.16017465, -2.1050534 ],
        ...,
        [ 1.4473416 ,  1.2453166 , -0.05608365],
        [ 0.48070228,  0.21038947,  0.5693352 ],
        [ 1.1329907 , -0.10074199, -0.4262918 ]],

       [[-1.0017619 , -0.4130074 ,  1.9709021 ],
        [ 1.1261594 ,  0.8030445 , -0.13455918],
        [ 1.4553814 , -0.7077329 , -0.14673623],
        ...,
        [-1.5051513 , -0.86866486,  0.7910269 ],
        [ 0.95673156,  0.9247523 ,  1.0401778 ],
        [-0.03240187, -0.126545  ,  1.3657708 ]],

       [[ 0.61522555,  0.21104665,  0.92734694],
        [ 1.0903655 ,  2.8252933 , -2.4538727 ],
        [ 0.7269391 , -0.90018594, -0.48686114],
        ...,
        [ 0.2720648 ,  0.39592102,  0.13167113],
        [ 0.41388002, -0.5150849 , -0.96912825],
        [ 1.2204841 ,  1.5515296 , -0.14588062]],

       ...,

     

In [63]:
E = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
E.reduce_argmax()

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'reduce_argmax'